# Generated by Django 3.0.6 on 2020-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200618_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='map_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
