# Generated by Django 3.0.6 on 2020-06-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200622_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='map_model',
            new_name='Location',
        ),
    ]
